### ISSUE TITLE
Dates overlapping on analysing using CLI application

### ISSUE THREAD

**Issue by Sanket-Mathur** [Sanket-Mathur/Work-Hours-Analysis#5]
## Description
The dates represented on the x-axis are overlapped and hence not visible when using the CLI application

## Screenshot
![Figure_1](https://user-images.githubusercontent.com/52062536/135354761-557b9af2-851c-43d8-87ad-abf94020a8a8.png)

## Steps to replicate
Using the terminal in the root directory of the folder
```
cd '.\CLI Application\'
python .\analyse.py
```

**Comment by Bipul-Harsh** [comment]
So you want that date should be rotated or resized?

**Comment by Sanket-Mathur** [comment]
Well done @Bipul-Harsh. Thanks for another contribution to the project.
